// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using R_FACTORY_BE.Models.Models;

namespace R_FACTORY_BE.Models.Context;

public partial class rtc_factory_oeeContext : DbContext
{
    public rtc_factory_oeeContext(DbContextOptions<rtc_factory_oeeContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Area> Areas { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Factory> Factories { get; set; }

    public virtual DbSet<FormAndFunction> FormAndFunctions { get; set; }

    public virtual DbSet<FormAndFunctionGroup> FormAndFunctionGroups { get; set; }

    public virtual DbSet<Line> Lines { get; set; }

    public virtual DbSet<Machine> Machines { get; set; }

    public virtual DbSet<MachineDowntimeEvent> MachineDowntimeEvents { get; set; }

    public virtual DbSet<MachineStatusLog> MachineStatusLogs { get; set; }

    public virtual DbSet<MachineType> MachineTypes { get; set; }

    public virtual DbSet<Menu> Menus { get; set; }

    public virtual DbSet<Model> Models { get; set; }

    public virtual DbSet<ModelMachineCycleTime> ModelMachineCycleTimes { get; set; }

    public virtual DbSet<Organization> Organizations { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<PlannedDowntimeSchedule> PlannedDowntimeSchedules { get; set; }

    public virtual DbSet<PlannedDowntimeType> PlannedDowntimeTypes { get; set; }

    public virtual DbSet<ProductionOutputLog> ProductionOutputLogs { get; set; }

    public virtual DbSet<ProductionPlan> ProductionPlans { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RolePermission> RolePermissions { get; set; }

    public virtual DbSet<Shift> Shifts { get; set; }

    public virtual DbSet<UnplannedDowntimeReason> UnplannedDowntimeReasons { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserGroup> UserGroups { get; set; }

    public virtual DbSet<UserGroupLink> UserGroupLinks { get; set; }

    public virtual DbSet<UserGroupRightDistribution> UserGroupRightDistributions { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<Area>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("areas");

            entity.HasIndex(e => e.FactoryId, "ix_areas_factory_id");

            entity.HasIndex(e => e.AreaName, "ix_areas_name");

            entity.HasIndex(e => e.AreaCode, "uk_areas_code").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AreaCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("area_code");
            entity.Property(e => e.AreaName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("area_name");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasColumnName("description");
            entity.Property(e => e.FactoryId).HasColumnName("factory_id");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_active");
            entity.Property(e => e.LayoutImagePath)
                .HasMaxLength(1000)
                .HasColumnName("layout_image_path");
            entity.Property(e => e.SortOrder).HasColumnName("sort_order");
            entity.Property(e => e.UpdatedDate)
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("departments");

            entity.HasIndex(e => e.DepartmentCode, "uk_departments_code").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.DepartmentCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("department_code");
            entity.Property(e => e.DepartmentName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("department_name");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasColumnName("description");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_active");
            entity.Property(e => e.UpdatedDate)
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<Factory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("factories");

            entity.HasIndex(e => e.FactoryName, "ix_factories_name");

            entity.HasIndex(e => e.FactoryCode, "uk_factories_code").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address)
                .HasMaxLength(500)
                .HasColumnName("address");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasColumnName("description");
            entity.Property(e => e.FactoryCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("factory_code");
            entity.Property(e => e.FactoryName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("factory_name");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_active");
            entity.Property(e => e.UpdatedDate)
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<FormAndFunction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("form_and_function");

            entity.HasIndex(e => e.Code, "idx_Code_form_and_function");

            entity.HasIndex(e => e.FormAndFunctionGroupId, "idx_FormAndFunctionGroupID_form_and_function");

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(150)
                .UseCollation("utf8mb3_general_ci")
                .HasCharSet("utf8mb3");
            entity.Property(e => e.CreatedBy).HasMaxLength(20);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Description)
                .HasMaxLength(300)
                .UseCollation("utf8mb3_general_ci")
                .HasCharSet("utf8mb3");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(300)
                .UseCollation("utf8mb3_general_ci")
                .HasCharSet("utf8mb3");
            entity.Property(e => e.ShortcutKey)
                .HasMaxLength(20)
                .UseCollation("utf8mb3_general_ci")
                .HasCharSet("utf8mb3");
            entity.Property(e => e.UpdatedBy).HasMaxLength(20);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<FormAndFunctionGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("form_and_function_group");

            entity.HasIndex(e => e.ParentId, "idx_ParentID_form_and_function_group");

            entity.Property(e => e.Code)
                .HasMaxLength(500)
                .UseCollation("utf8mb3_general_ci")
                .HasCharSet("utf8mb3");
            entity.Property(e => e.CreatedBy).HasMaxLength(20);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .UseCollation("utf8mb3_general_ci")
                .HasCharSet("utf8mb3");
            entity.Property(e => e.Name)
                .HasMaxLength(500)
                .UseCollation("utf8mb3_general_ci")
                .HasCharSet("utf8mb3");
            entity.Property(e => e.ParentId).HasColumnName("ParentID");
            entity.Property(e => e.UpdatedBy).HasMaxLength(20);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Line>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("lines");

            entity.HasIndex(e => e.FactoryId, "ix_lines_factory_id");

            entity.HasIndex(e => e.LineName, "ix_lines_name");

            entity.HasIndex(e => e.AreaId, "ix_lines_area_id");

            entity.HasIndex(e => e.LineCode, "uk_lines_code").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.FactoryId).HasColumnName("factory_id");
            entity.Property(e => e.IsActive)
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_active");
            entity.Property(e => e.LineCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("line_code");
            entity.Property(e => e.LineName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("line_name");
            entity.Property(e => e.SortOrder).HasColumnName("sort_order");
            entity.Property(e => e.UpdatedDate)
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
            entity.Property(e => e.AreaId).HasColumnName("area_id");
        });

        modelBuilder.Entity<Machine>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("machines");

            entity.HasIndex(e => e.FactoryId, "ix_machines_factory_id");

            entity.HasIndex(e => e.LineId, "ix_machines_line_id");

            entity.HasIndex(e => e.MachineTypeId, "ix_machines_machine_type_id");

            entity.HasIndex(e => e.MachineName, "ix_machines_name");

            entity.HasIndex(e => e.MachineCode, "uk_machines_code").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasColumnName("description");
            entity.Property(e => e.FactoryId).HasColumnName("factory_id");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_active");
            entity.Property(e => e.LayoutHeight)
                .HasPrecision(10, 2)
                .HasColumnName("layout_height");
            entity.Property(e => e.LayoutWidth)
                .HasPrecision(10, 2)
                .HasColumnName("layout_width");
            entity.Property(e => e.LayoutX)
                .HasPrecision(10, 2)
                .HasColumnName("layout_x");
            entity.Property(e => e.LayoutY)
                .HasPrecision(10, 2)
                .HasColumnName("layout_y");
            entity.Property(e => e.LineId).HasColumnName("line_id");
            entity.Property(e => e.MachineCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("machine_code");
            entity.Property(e => e.MachineName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("machine_name");
            entity.Property(e => e.MachineTypeId).HasColumnName("machine_type_id");
            entity.Property(e => e.SerialNo)
                .HasMaxLength(100)
                .HasColumnName("serial_no");
            entity.Property(e => e.UpdatedDate)
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<MachineDowntimeEvent>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("machine_downtime_events");

            entity.HasIndex(e => e.DowntimeType, "ix_machine_downtime_events_downtime_type");

            entity.HasIndex(e => e.EndTime, "ix_machine_downtime_events_end_time");

            entity.HasIndex(e => e.FactoryId, "ix_machine_downtime_events_factory_id");

            entity.HasIndex(e => e.LineId, "ix_machine_downtime_events_line_id");

            entity.HasIndex(e => e.MachineId, "ix_machine_downtime_events_machine_id");

            entity.HasIndex(e => e.MachineStatusLogId, "ix_machine_downtime_events_machine_status_log_id");

            entity.HasIndex(e => e.PlannedDowntimeTypeId, "ix_machine_downtime_events_planned_type_id");

            entity.HasIndex(e => e.ProductionPlanId, "ix_machine_downtime_events_production_plan_id");

            entity.HasIndex(e => e.ShiftId, "ix_machine_downtime_events_shift_id");

            entity.HasIndex(e => e.StartTime, "ix_machine_downtime_events_start_time");

            entity.HasIndex(e => e.UnplannedDowntimeReasonId, "ix_machine_downtime_events_unplanned_reason_id");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CorrectiveAction)
                .HasMaxLength(1000)
                .HasColumnName("corrective_action");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.DowntimeType)
                .IsRequired()
                .HasColumnType("enum('planned','unplanned')")
                .HasColumnName("downtime_type");
            entity.Property(e => e.EndTime)
                .HasColumnType("datetime")
                .HasColumnName("end_time");
            entity.Property(e => e.FactoryId).HasColumnName("factory_id");
            entity.Property(e => e.LineId).HasColumnName("line_id");
            entity.Property(e => e.MachineId).HasColumnName("machine_id");
            entity.Property(e => e.MachineStatusLogId).HasColumnName("machine_status_log_id");
            entity.Property(e => e.Note)
                .HasMaxLength(1000)
                .HasColumnName("note");
            entity.Property(e => e.PlannedDowntimeTypeId).HasColumnName("planned_downtime_type_id");
            entity.Property(e => e.ProductionPlanId).HasColumnName("production_plan_id");
            entity.Property(e => e.RootCause)
                .HasMaxLength(1000)
                .HasColumnName("root_cause");
            entity.Property(e => e.ShiftId).HasColumnName("shift_id");
            entity.Property(e => e.StartTime)
                .HasColumnType("datetime")
                .HasColumnName("start_time");
            entity.Property(e => e.UnplannedDowntimeReasonId).HasColumnName("unplanned_downtime_reason_id");
            entity.Property(e => e.UpdatedDate)
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<MachineStatusLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("machine_status_logs");

            entity.HasIndex(e => e.EndTime, "ix_machine_status_logs_end_time");

            entity.HasIndex(e => e.FactoryId, "ix_machine_status_logs_factory_id");

            entity.HasIndex(e => e.LineId, "ix_machine_status_logs_line_id");

            entity.HasIndex(e => e.MachineId, "ix_machine_status_logs_machine_id");

            entity.HasIndex(e => e.ProductionPlanId, "ix_machine_status_logs_production_plan_id");

            entity.HasIndex(e => e.ShiftId, "ix_machine_status_logs_shift_id");

            entity.HasIndex(e => e.StartTime, "ix_machine_status_logs_start_time");

            entity.HasIndex(e => e.Status, "ix_machine_status_logs_status");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.EndTime)
                .HasColumnType("datetime")
                .HasColumnName("end_time");
            entity.Property(e => e.FactoryId).HasColumnName("factory_id");
            entity.Property(e => e.LineId).HasColumnName("line_id");
            entity.Property(e => e.MachineId).HasColumnName("machine_id");
            entity.Property(e => e.ProductionPlanId).HasColumnName("production_plan_id");
            entity.Property(e => e.RawData)
                .HasColumnType("json")
                .HasColumnName("raw_data");
            entity.Property(e => e.ShiftId).HasColumnName("shift_id");
            entity.Property(e => e.SourceType)
                .IsRequired()
                .HasDefaultValueSql("'api'")
                .HasColumnType("enum('api','manual','plc','system')")
                .HasColumnName("source_type");
            entity.Property(e => e.StartTime)
                .HasColumnType("datetime")
                .HasColumnName("start_time");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasColumnType("enum('running','stopped','idle','offline','setup','maintenance')")
                .HasColumnName("status");
        });

        modelBuilder.Entity<MachineType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("machine_types");

            entity.HasIndex(e => e.MachineTypeCode, "uk_machine_types_code").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasColumnName("description");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_active");
            entity.Property(e => e.MachineTypeCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("machine_type_code");
            entity.Property(e => e.MachineTypeName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("machine_type_name");
            entity.Property(e => e.UpdatedDate)
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<Menu>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("menu");

            entity.HasIndex(e => e.ParentMenuId, "IX_menu_ParentMenuId");

            entity.Property(e => e.CreatedBy).HasMaxLength(255);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Icon).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(255);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.ParentMenu).WithMany(p => p.InverseParentMenu).HasForeignKey(d => d.ParentMenuId);
        });

        modelBuilder.Entity<Model>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("models");

            entity.HasIndex(e => e.ModelName, "ix_models_name");

            entity.HasIndex(e => e.ModelCode, "uk_models_code").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasColumnName("description");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_active");
            entity.Property(e => e.ModelCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("model_code");
            entity.Property(e => e.ModelName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("model_name");
            entity.Property(e => e.UpdatedDate)
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<ModelMachineCycleTime>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("model_machine_cycle_times");

            entity.HasIndex(e => e.MachineId, "ix_model_machine_cycle_times_machine_id");

            entity.HasIndex(e => e.ModelId, "ix_model_machine_cycle_times_model_id");

            entity.HasIndex(e => new { e.ModelId, e.MachineId }, "uk_model_machine_cycle_times_model_machine").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.IdealCycleTimeSeconds)
                .HasPrecision(18, 4)
                .HasColumnName("ideal_cycle_time_seconds");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_active");
            entity.Property(e => e.MachineId).HasColumnName("machine_id");
            entity.Property(e => e.ModelId).HasColumnName("model_id");
            entity.Property(e => e.UpdatedDate)
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<Organization>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("organizations");

            entity.HasIndex(e => e.ParentId, "idx_ParentID_department");

            entity.Property(e => e.CreatedDate).HasMaxLength(6);
            entity.Property(e => e.OrganizationCode)
                .HasMaxLength(50)
                .UseCollation("utf8mb3_general_ci")
                .HasCharSet("utf8mb3");
            entity.Property(e => e.OrganizationName)
                .HasMaxLength(255)
                .UseCollation("utf8mb3_general_ci")
                .HasCharSet("utf8mb3");
            entity.Property(e => e.UpdatedDate).HasMaxLength(6);
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("permissions");

            entity.HasIndex(e => e.ModuleName, "ix_permissions_module_name");

            entity.HasIndex(e => e.PermissionCode, "uk_permissions_code").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasColumnName("description");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_active");
            entity.Property(e => e.ModuleName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("module_name");
            entity.Property(e => e.PermissionCode)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("permission_code");
            entity.Property(e => e.PermissionName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("permission_name");
            entity.Property(e => e.UpdatedDate)
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<PlannedDowntimeSchedule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("planned_downtime_schedules");

            entity.HasIndex(e => e.EndTime, "ix_planned_downtime_schedules_end_time");

            entity.HasIndex(e => e.FactoryId, "ix_planned_downtime_schedules_factory_id");

            entity.HasIndex(e => e.LineId, "ix_planned_downtime_schedules_line_id");

            entity.HasIndex(e => e.MachineId, "ix_planned_downtime_schedules_machine_id");

            entity.HasIndex(e => e.ShiftId, "ix_planned_downtime_schedules_shift_id");

            entity.HasIndex(e => e.StartTime, "ix_planned_downtime_schedules_start_time");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasColumnName("description");
            entity.Property(e => e.EndTime)
                .HasColumnType("datetime")
                .HasColumnName("end_time");
            entity.Property(e => e.FactoryId).HasColumnName("factory_id");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_active");
            entity.Property(e => e.LineId).HasColumnName("line_id");
            entity.Property(e => e.MachineId).HasColumnName("machine_id");
            entity.Property(e => e.PlannedDowntimeTypeId).HasColumnName("planned_downtime_type_id");
            entity.Property(e => e.ShiftId).HasColumnName("shift_id");
            entity.Property(e => e.StartTime)
                .HasColumnType("datetime")
                .HasColumnName("start_time");
            entity.Property(e => e.UpdatedDate)
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<PlannedDowntimeType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("planned_downtime_types");

            entity.HasIndex(e => e.Code, "uk_planned_downtime_types_code").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("code");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasColumnName("description");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_active");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("name");
            entity.Property(e => e.UpdatedDate)
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<ProductionOutputLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("production_output_logs");

            entity.HasIndex(e => e.FactoryId, "ix_production_output_logs_factory_id");

            entity.HasIndex(e => e.LineId, "ix_production_output_logs_line_id");

            entity.HasIndex(e => e.LogTime, "ix_production_output_logs_log_time");

            entity.HasIndex(e => e.MachineId, "ix_production_output_logs_machine_id");

            entity.HasIndex(e => e.ModelId, "ix_production_output_logs_model_id");

            entity.HasIndex(e => e.ProductionPlanId, "ix_production_output_logs_production_plan_id");

            entity.HasIndex(e => e.ShiftId, "ix_production_output_logs_shift_id");

            entity.HasIndex(e => e.SourceType, "ix_production_output_logs_source_type");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.FactoryId).HasColumnName("factory_id");
            entity.Property(e => e.GoodQty).HasColumnName("good_qty");
            entity.Property(e => e.LineId).HasColumnName("line_id");
            entity.Property(e => e.LogTime)
                .HasColumnType("datetime")
                .HasColumnName("log_time");
            entity.Property(e => e.MachineId).HasColumnName("machine_id");
            entity.Property(e => e.ModelId).HasColumnName("model_id");
            entity.Property(e => e.NgQty).HasColumnName("ng_qty");
            entity.Property(e => e.ProductionPlanId).HasColumnName("production_plan_id");
            entity.Property(e => e.RawData)
                .HasColumnType("json")
                .HasColumnName("raw_data");
            entity.Property(e => e.ShiftId).HasColumnName("shift_id");
            entity.Property(e => e.SourceType)
                .IsRequired()
                .HasDefaultValueSql("'api'")
                .HasColumnType("enum('api','manual','plc','import')")
                .HasColumnName("source_type");
            entity.Property(e => e.TotalQty)
                .HasComputedColumnSql("`good_qty` + `ng_qty`", true)
                .HasColumnName("total_qty");
        });

        modelBuilder.Entity<ProductionPlan>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("production_plans");

            entity.HasIndex(e => e.ActualEndTime, "ix_production_plans_actual_end_time");

            entity.HasIndex(e => e.ActualStartTime, "ix_production_plans_actual_start_time");

            entity.HasIndex(e => e.FactoryId, "ix_production_plans_factory_id");

            entity.HasIndex(e => e.LineId, "ix_production_plans_line_id");

            entity.HasIndex(e => e.MachineId, "ix_production_plans_machine_id");

            entity.HasIndex(e => e.ModelId, "ix_production_plans_model_id");

            entity.HasIndex(e => e.PlannedEndTime, "ix_production_plans_planned_end_time");

            entity.HasIndex(e => e.PlannedStartTime, "ix_production_plans_planned_start_time");

            entity.HasIndex(e => e.ShiftId, "ix_production_plans_shift_id");

            entity.HasIndex(e => e.Status, "ix_production_plans_status");

            entity.HasIndex(e => e.PlanCode, "uk_production_plans_code").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ActualEndTime)
                .HasColumnType("datetime")
                .HasColumnName("actual_end_time");
            entity.Property(e => e.ActualStartTime)
                .HasColumnType("datetime")
                .HasColumnName("actual_start_time");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.FactoryId).HasColumnName("factory_id");
            entity.Property(e => e.LineId).HasColumnName("line_id");
            entity.Property(e => e.MachineId).HasColumnName("machine_id");
            entity.Property(e => e.ModelId).HasColumnName("model_id");
            entity.Property(e => e.PlanCode)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("plan_code");
            entity.Property(e => e.PlannedEndTime)
                .HasColumnType("datetime")
                .HasColumnName("planned_end_time");
            entity.Property(e => e.PlannedQty).HasColumnName("planned_qty");
            entity.Property(e => e.PlannedStartTime)
                .HasColumnType("datetime")
                .HasColumnName("planned_start_time");
            entity.Property(e => e.ShiftId).HasColumnName("shift_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasDefaultValueSql("'draft'")
                .HasColumnType("enum('draft','scheduled','running','completed','cancelled')")
                .HasColumnName("status");
            entity.Property(e => e.UpdatedDate)
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("roles");

            entity.HasIndex(e => e.RoleCode, "uk_roles_code").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasColumnName("description");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_active");
            entity.Property(e => e.RoleCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("role_code");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("role_name");
            entity.Property(e => e.UpdatedDate)
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<RolePermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("role_permissions");

            entity.HasIndex(e => e.PermissionId, "ix_role_permissions_permission_id");

            entity.HasIndex(e => e.RoleId, "ix_role_permissions_role_id");

            entity.HasIndex(e => new { e.RoleId, e.PermissionId }, "uk_role_permissions_role_permission").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CanCreate).HasColumnName("can_create");
            entity.Property(e => e.CanDelete).HasColumnName("can_delete");
            entity.Property(e => e.CanExport).HasColumnName("can_export");
            entity.Property(e => e.CanUpdate).HasColumnName("can_update");
            entity.Property(e => e.CanView)
                .IsRequired()
                .HasDefaultValueSql("'1'")
                .HasColumnName("can_view");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.PermissionId).HasColumnName("permission_id");
            entity.Property(e => e.RoleId).HasColumnName("role_id");
        });

        modelBuilder.Entity<Shift>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("shifts");

            entity.HasIndex(e => e.ShiftCode, "uk_shifts_code").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasColumnName("description");
            entity.Property(e => e.EndTime)
                .HasColumnType("time")
                .HasColumnName("end_time");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_active");
            entity.Property(e => e.ShiftCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("shift_code");
            entity.Property(e => e.ShiftName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("shift_name");
            entity.Property(e => e.StartTime)
                .HasColumnType("time")
                .HasColumnName("start_time");
            entity.Property(e => e.UpdatedDate)
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<UnplannedDowntimeReason>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("unplanned_downtime_reasons");

            entity.HasIndex(e => e.Code, "uk_unplanned_downtime_reasons_code").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("code");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasColumnName("description");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_active");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("name");
            entity.Property(e => e.UpdatedDate)
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("users");

            entity.HasIndex(e => e.DepartmentId, "ix_users_department_id");

            entity.HasIndex(e => e.FullName, "ix_users_full_name");

            entity.HasIndex(e => e.Username, "uk_users_username").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.DepartmentId).HasColumnName("department_id");
            entity.Property(e => e.Email)
                .HasMaxLength(200)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("full_name");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_active");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("password_hash");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(50)
                .HasColumnName("phone_number");
            entity.Property(e => e.UpdatedDate)
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("username");
        });

        modelBuilder.Entity<UserGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("user_group");

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(255);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(255);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<UserGroupLink>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("user_group_link");

            entity.Property(e => e.CreatedDate).HasMaxLength(6);
            entity.Property(e => e.UpdatedDate).HasMaxLength(6);
        });

        modelBuilder.Entity<UserGroupRightDistribution>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("user_group_right_distribution");

            entity.Property(e => e.CreatedDate).HasMaxLength(6);
            entity.Property(e => e.UpdatedDate).HasMaxLength(6);
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("user_roles");

            entity.HasIndex(e => e.RoleId, "ix_user_roles_role_id");

            entity.HasIndex(e => e.UserId, "ix_user_roles_user_id");

            entity.HasIndex(e => new { e.UserId, e.RoleId }, "uk_user_roles_user_role").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");
        });

        modelBuilder.Entity<Zone>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("zones");

            entity.HasIndex(e => e.FactoryId, "ix_zones_factory_id");

            entity.HasIndex(e => e.ZoneName, "ix_zones_name");

            entity.HasIndex(e => e.ZoneCode, "uk_zones_code").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasColumnName("description");
            entity.Property(e => e.FactoryId).HasColumnName("factory_id");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_active");
            entity.Property(e => e.LayoutImagePath)
                .HasMaxLength(1000)
                .HasColumnName("layout_image_path");
            entity.Property(e => e.SortOrder).HasColumnName("sort_order");
            entity.Property(e => e.UpdatedDate)
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
            entity.Property(e => e.ZoneCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("zone_code");
            entity.Property(e => e.ZoneName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("zone_name");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
