// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_FACTORY_BE.Models.Models;

public partial class Area
{
    public int Id { get; set; }

    public int FactoryId { get; set; }

    public string AreaCode { get; set; }

    public string AreaName { get; set; }

    public string LayoutImagePath { get; set; }

    public string Description { get; set; }

    public int SortOrder { get; set; }

    public bool? IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }
}