// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_FACTORY_BE.Models.Models;

public partial class FormAndFunction
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool? ShiftKey { get; set; }

    public bool? CtrlKey { get; set; }

    public bool? AltKey { get; set; }

    public string ShortcutKey { get; set; }

    public int? FormAndFunctionGroupId { get; set; }

    public bool IsHide { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool IsDeleted { get; set; }
}