// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_FACTORY_BE.Models.Models;

public partial class MachineStatusLog
{
    public long Id { get; set; }

    public int FactoryId { get; set; }

    public int LineId { get; set; }

    public int MachineId { get; set; }

    public long? ProductionPlanId { get; set; }

    public int? ShiftId { get; set; }

    public string Status { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string SourceType { get; set; }

    public string RawData { get; set; }

    public DateTime CreatedDate { get; set; }
}