// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_FACTORY_BE.Models.Models;

public partial class MachineDowntimeEvent
{
    public long Id { get; set; }

    public int FactoryId { get; set; }

    public int LineId { get; set; }

    public int MachineId { get; set; }

    public long? ProductionPlanId { get; set; }

    public long? MachineStatusLogId { get; set; }

    public int? ShiftId { get; set; }

    public string DowntimeType { get; set; }

    public int? PlannedDowntimeTypeId { get; set; }

    public int? UnplannedDowntimeReasonId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string RootCause { get; set; }

    public string CorrectiveAction { get; set; }

    public string Note { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }
}