// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_FACTORY_BE.Models.Models;

public partial class Menu
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string NameEn { get; set; }

    public string Url { get; set; }

    public string Icon { get; set; }

    public int Order { get; set; }

    public int? ParentMenuId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<Menu> InverseParentMenu { get; set; } = new List<Menu>();

    public virtual Menu ParentMenu { get; set; }
}