// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_FACTORY_BE.Models.Models;

public partial class ModelMachineCycleTime
{
    public int Id { get; set; }

    public int ModelId { get; set; }

    public int MachineId { get; set; }

    public decimal IdealCycleTimeSeconds { get; set; }

    public bool? IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }
}