// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_FACTORY_BE.Models.Models;

public partial class PlannedDowntimeSchedule
{
    public long Id { get; set; }

    public int FactoryId { get; set; }

    public int? LineId { get; set; }

    public int? MachineId { get; set; }

    public int? ShiftId { get; set; }

    public int PlannedDowntimeTypeId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }
}