// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_FACTORY_BE.Models.Models;

public partial class ProductionOutputLog
{
    public long Id { get; set; }

    public int FactoryId { get; set; }

    public int LineId { get; set; }

    public int MachineId { get; set; }

    public int? ModelId { get; set; }

    public long? ProductionPlanId { get; set; }

    public int? ShiftId { get; set; }

    public int GoodQty { get; set; }

    public int NgQty { get; set; }

    public int? TotalQty { get; set; }

    public DateTime LogTime { get; set; }

    public string SourceType { get; set; }

    public string RawData { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }
}