// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_FACTORY_BE.Models.Models;

public partial class ProductionPlan
{
    public long Id { get; set; }

    public string PlanCode { get; set; }

    public int FactoryId { get; set; }

    public int LineId { get; set; }

    public int MachineId { get; set; }

    public int ModelId { get; set; }

    public int? ShiftId { get; set; }

    public int PlannedQty { get; set; }

    public DateTime PlannedStartTime { get; set; }

    public DateTime PlannedEndTime { get; set; }

    public DateTime? ActualStartTime { get; set; }

    public DateTime? ActualEndTime { get; set; }

    public string Status { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }
}