// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_FACTORY_BE.Models.Models;

/// <summary>
/// Stores hashed refresh tokens with rotation/revocation support
/// </summary>
public partial class RefreshToken
{
    public ulong Id { get; set; }

    public int UserId { get; set; }

    /// <summary>
    /// SHA-256 hash of raw token
    /// </summary>
    public string TokenHash { get; set; }

    /// <summary>
    /// User-Agent or IP info
    /// </summary>
    public string DeviceInfo { get; set; }

    public DateTime IssuedAt { get; set; }

    public DateTime ExpiresAt { get; set; }

    /// <summary>
    /// Set when token is revoked/rotated
    /// </summary>
    public DateTime? RevokedAt { get; set; }

    /// <summary>
    /// IPv4/IPv6 of revoker
    /// </summary>
    public string RevokedByIp { get; set; }

    /// <summary>
    /// Hash of newer token (for rotation chain)
    /// </summary>
    public string ReplacedByTokenHash { get; set; }

    /// <summary>
    /// logout | rotation | reuse_detected | expired
    /// </summary>
    public string ReasonRevoked { get; set; }
}