// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_FACTORY_BE.Models.Models;

public partial class RolePermission
{
    public long Id { get; set; }

    public int RoleId { get; set; }

    public int PermissionId { get; set; }

    public bool? CanView { get; set; }

    public bool CanCreate { get; set; }

    public bool CanUpdate { get; set; }

    public bool CanDelete { get; set; }

    public bool CanExport { get; set; }

    public DateTime CreatedDate { get; set; }
}