// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_FACTORY_BE.Models.Models;

/// <summary>
/// Cached user permissions from spPermission (invalidated on group changes)
/// </summary>
public partial class UserPermission
{
    public ulong Id { get; set; }

    public uint UserId { get; set; }

    /// <summary>
    /// Code từ form_and_function.Code
    /// </summary>
    public string PermissionCode { get; set; }

    public DateTime GrantedAt { get; set; }
}