// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_FACTORY_BE.Models.Models;

public partial class UserRole
{
    public long Id { get; set; }

    public int UserId { get; set; }

    public int RoleId { get; set; }

    public DateTime CreatedDate { get; set; }
}